import React, { useEffect, useMemo, useState } from 'react';
import { Bell, CalendarDays, CalendarClock, CheckCircle2, ChevronRight, ClipboardList, Download, FileText, LayoutDashboard, ListTodo, MessageSquare, Settings2, ShieldCheck, TriangleAlert, UploadCloud, Users, X } from 'lucide-react';

const projects = [
  { name: 'Project BC-08-26', client: 'Northstar Builders', progress: 68, due: 'Today, 4:00 PM', dueAt: '2026-09-21T16:00:00', status: 'At risk', color: 'text-[#f0b44d]' },
  { name: 'Metro Heights — Shop Drawings', client: 'Turner Construction', progress: 42, due: 'Tomorrow', dueAt: '2026-09-22T17:00:00', status: 'On track', color: 'text-[#4edea3]' },
  { name: 'Civic Centre Takeoff', client: 'CityWorks', progress: 84, due: 'Sep 25', dueAt: '2026-09-25T17:00:00', status: 'On track', color: 'text-[#4edea3]' },
];
const tasks = [
  { title: 'Resolve RFI-042: slab penetration detail', project: 'Project BC-08-26', due: 'Due today', urgent: true },
  { title: 'Upload revised Level 03 shop drawings', project: 'Metro Heights', due: 'Due tomorrow', urgent: false },
  { title: 'Review concrete quantities with Omar', project: 'Civic Centre Takeoff', due: 'Sep 24', urgent: false },
];
const materialList = [
  { name: 'Ready-mix concrete 4,000 PSI', code: 'MAT-CON-4000', unit: 'CY', price: 185 },
  { name: 'Rebar #5 Grade 60', code: 'MAT-REB-005', unit: 'LB', price: 0.92 },
  { name: 'Structural steel W-section', code: 'MAT-STL-W', unit: 'TON', price: 2450 },
  { name: 'Copper THHN wire 500 kcmil', code: 'MAT-ELE-500', unit: 'LF', price: 8.45 },
];
const menu = [
  { id: 'overview', label: 'Overview', icon: LayoutDashboard },
  { id: 'projects', label: 'My projects', icon: ClipboardList, count: '3' },
  { id: 'tasks', label: 'Assigned tasks', icon: ListTodo, count: '5' },
  { id: 'estimates', label: 'Estimation workspace', icon: FileText },
  { id: 'rfis', label: 'RFIs & responses', icon: MessageSquare, count: '1' },
  { id: 'notifications', label: 'Notifications', icon: Bell, count: '2' },
  { id: 'reminders', label: 'Reminders', icon: CalendarClock },
  { id: 'leave', label: 'Leave requests', icon: CalendarDays },
];

type MenuId = typeof menu[number]['id'] | 'admin';

interface EmployeePortalViewProps {
  currentUser?: {
    name: string;
    title?: string;
    department?: string;
    email?: string;
  };
}

export function EmployeePortalView({ currentUser }: EmployeePortalViewProps = {}) {
  const [activeMenu, setActiveMenu] = useState<MenuId>('overview');
  const [currentTime, setCurrentTime] = useState(() => Date.now());
  const [taskState, setTaskState] = useState<Record<string, boolean>>({});
  const [openTask, setOpenTask] = useState<typeof tasks[number] | null>(null);
  const [materialSearch, setMaterialSearch] = useState('');
  const [estimateMaterials, setEstimateMaterials] = useState<string[]>([]);
  const [adminMode, setAdminMode] = useState(false);
  const [leaveNotice, setLeaveNotice] = useState('');

  const displayName = currentUser?.name || 'Maya Chen';
  const displayTitle = currentUser?.title || 'Senior Estimator · Estimating Team';
  useEffect(() => { const interval = window.setInterval(() => setCurrentTime(Date.now()), 1000); return () => window.clearInterval(interval); }, []);
  const visibleMaterials = useMemo(() => materialList.filter((item) => `${item.name} ${item.code}`.toLowerCase().includes(materialSearch.toLowerCase())), [materialSearch]);
  const formatDueCountdown = (dueAt: string) => { const minutes = Math.max(0, Math.floor((new Date(dueAt).getTime() - currentTime) / 60000)); return `${String(Math.floor(minutes / 1440)).padStart(2, '0')}d ${String(Math.floor((minutes % 1440) / 60)).padStart(2, '0')}h ${String(minutes % 60).padStart(2, '0')}m`; };
  const toggleTask = (title: string) => setTaskState((state) => ({ ...state, [title]: !state[title] }));
  const jump = (id: MenuId) => { setActiveMenu(id); document.getElementById(`employee-${id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };

  return (
    <div className="min-h-full bg-[#080d18] text-[#dae2fd]">
      <div className="flex min-h-full">
        <aside className="hidden w-64 shrink-0 border-r border-[#222a3d] bg-[#0b1326] lg:flex lg:flex-col">
          <div className="border-b border-[#222a3d] p-5"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#4edea3]/10 text-[#4edea3]"><ShieldCheck className="h-5 w-5" /></div><div><p className="text-sm font-bold text-white">Employee workspace</p><p className="text-[10px] uppercase tracking-widest text-[#4edea3]">Bid Exact LLC</p></div></div></div>
          <div className="border-b border-[#222a3d] p-4"><p className="text-[10px] uppercase tracking-widest text-[#86948a]">Signed in as</p><p className="mt-1 text-sm font-semibold text-white">{displayName}</p><p className="text-[11px] text-[#86948a]">{displayTitle}</p></div>
          <nav className="flex-1 space-y-1 overflow-y-auto p-3" aria-label="Employee portal navigation"><p className="px-3 pb-2 pt-2 text-[10px] font-semibold uppercase tracking-widest text-[#667085]">Work center</p>{menu.map(({ id, label, icon: Icon, count }) => <button key={id} type="button" onClick={() => jump(id)} className={`flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-xs transition ${activeMenu === id ? 'bg-[#4edea3]/10 text-white ring-1 ring-[#4edea3]/20' : 'text-[#aeb8c8] hover:bg-[#131b2e] hover:text-white'}`}><span className="flex items-center gap-3"><Icon className={`h-4 w-4 ${activeMenu === id ? 'text-[#4edea3]' : 'text-[#718096]'}`} />{label}</span>{count && <span className="rounded bg-[#202b42] px-1.5 py-0.5 font-mono text-[9px] text-[#bbcabf]">{count}</span>}</button>)}<p className="px-3 pb-2 pt-6 text-[10px] font-semibold uppercase tracking-widest text-[#667085]">Administration</p><button type="button" onClick={() => { setAdminMode(true); setActiveMenu('admin'); window.setTimeout(() => document.getElementById('employee-admin')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-xs ${adminMode ? 'bg-[#7db2ff]/10 text-white ring-1 ring-[#7db2ff]/20' : 'text-[#aeb8c8] hover:bg-[#131b2e]'}`}><Settings2 className="h-4 w-4 text-[#7db2ff]" />Portal configuration</button></nav>
          <div className="m-3 rounded-xl border border-[#222a3d] bg-[#0d1728] p-3"><p className="text-[10px] text-[#86948a]">Team capacity</p><div className="mt-2 h-1.5 rounded-full bg-[#222a3d]"><div className="h-1.5 w-[40%] rounded-full bg-[#4edea3]" /></div><p className="mt-2 text-[10px] text-[#4edea3]">40% available this week</p></div>
        </aside>
        <main className="min-w-0 flex-1 p-4 md:p-7"><div className="mx-auto max-w-[1400px] space-y-6">
          <header className="flex flex-col gap-4 border-b border-[#222a3d] pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-mono uppercase tracking-[0.24em] text-[#4edea3]">Employee operations / today</p><h1 className="mt-2 text-2xl font-semibold tracking-tight text-white">Good morning, {displayName.split(' ')[0]}.</h1><p className="mt-1 text-sm text-[#86948a]">Everything assigned to you, organized by the estimating team workflow.</p></div><div className="flex items-center gap-2 rounded-xl border border-[#4edea3]/20 bg-[#0d1728] px-3 py-2 text-xs"><span className="h-2 w-2 rounded-full bg-[#4edea3]" /><span className="text-[#bbcabf]">Available for work</span><span className="font-mono text-[#4edea3]">40% capacity</span></div></header>
          <div className="flex gap-2 overflow-x-auto pb-1 lg:hidden">{menu.slice(0, 6).map(({ id, label }) => <button key={id} type="button" onClick={() => jump(id)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-[10px] ${activeMenu === id ? 'bg-[#4edea3] font-bold text-[#07101f]' : 'border border-[#2b3851] text-[#bbcabf]'}`}>{label}</button>)}</div>
          <section id="employee-overview" className="grid scroll-mt-5 gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['3', 'Active projects', '1 due today'], ['5', 'Open tasks', '2 high priority'], ['2', 'Unread notifications', '1 client thread'], ['06:30', 'Hours this week', 'of 40:00 target']].map(([value, label, note]) => <div key={label} className="rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4"><p className="text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs font-medium text-[#bbcabf]">{label}</p><p className="mt-2 text-[10px] font-mono text-[#4edea3]">{note}</p></div>)}</section>
          <section id="employee-projects" className="scroll-mt-5 rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4 md:p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-mono uppercase tracking-wider text-[#86948a]">Assigned portfolio</p><h2 className="mt-1 text-lg font-semibold text-white">My active projects</h2></div><span className="text-xs text-[#4edea3]">3 assigned</span></div><div className="mt-4 grid gap-3 xl:grid-cols-3">{projects.map((project) => <article key={project.name} className="rounded-xl border border-[#222a3d] bg-[#0a1220] p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="text-sm font-semibold text-white">{project.name}</h3><p className="mt-1 text-xs text-[#86948a]">{project.client}</p></div><span className={`text-[10px] font-mono uppercase ${project.color}`}>{project.status}</span></div><div className="mt-4 flex items-center gap-3"><div className="h-1.5 flex-1 rounded-full bg-[#222a3d]"><div className="h-1.5 rounded-full bg-[#4edea3]" style={{ width: `${project.progress}%` }} /></div><span className="text-[10px] font-mono text-[#bbcabf]">{project.progress}%</span></div><div className="mt-3 flex items-center justify-between text-[10px] text-[#86948a]"><span>Finish by {project.due}</span><span className="font-mono text-[#f0b44d]">{formatDueCountdown(project.dueAt)}</span></div><a href={`data:text/plain;charset=utf-8,Project%20files%20for%20${encodeURIComponent(project.name)}`} download={`${project.name.replaceAll(' ', '-')}-files.txt`} className="mt-3 inline-flex items-center gap-1 text-[10px] font-semibold text-[#7db2ff]"><Download className="h-3 w-3" /> Download files</a></article>)}</div></section>
          <div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><section id="employee-tasks" className="scroll-mt-5 rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4 md:p-5"><p className="text-[10px] font-mono uppercase tracking-wider text-[#86948a]">Today</p><h2 className="mt-1 text-lg font-semibold text-white">Assigned tasks</h2><div className="mt-4 space-y-3">{tasks.map((task) => <div key={task.title} className="flex items-start gap-2"><button type="button" onClick={() => toggleTask(task.title)} className="flex min-w-0 flex-1 items-start gap-3 text-left"><span className={`mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full border ${taskState[task.title] ? 'border-[#4edea3] bg-[#4edea3] text-[#07101f]' : 'border-[#526078]'}`}>{taskState[task.title] && <CheckCircle2 className="h-3 w-3" />}</span><span className={taskState[task.title] ? 'opacity-50 line-through' : ''}><span className="block text-xs font-medium text-white">{task.title}</span><span className={`mt-1 block text-[10px] font-mono ${task.urgent ? 'text-[#f0b44d]' : 'text-[#86948a]'}`}>{task.project} · {task.due}</span></span></button><button type="button" onClick={() => setOpenTask(task)} className="shrink-0 rounded-md border border-[#2b3851] px-2 py-1 text-[10px] font-semibold text-[#7db2ff]">Open</button></div>)}</div></section><section id="employee-notifications" className="scroll-mt-5 rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4 md:p-5"><p className="text-[10px] font-mono uppercase tracking-wider text-[#86948a]">Inbox</p><h2 className="mt-1 text-lg font-semibold text-white">Notifications</h2><div className="mt-4 space-y-2"><div className="rounded-xl border border-[#f0b44d]/20 bg-[#f0b44d]/10 p-3"><p className="text-xs font-semibold text-[#f0b44d]">RFI-042 needs response</p><p className="mt-1 text-[10px] text-[#d7c99d]">Northstar Builders is waiting on slab penetration detail.</p></div><div className="rounded-xl bg-[#0a1220] p-3"><p className="text-xs font-semibold text-white">Team lead assigned a new review</p><p className="mt-1 text-[10px] text-[#86948a]">Review Metro Heights Level 03 drawings.</p></div></div></section></div>
          <div className="grid gap-6 lg:grid-cols-2"><section id="employee-estimates" className="scroll-mt-5 rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4 md:p-5"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-[#4edea3]" /><h2 className="text-sm font-semibold text-white">Estimation workspace</h2></div><p className="mt-1 text-[10px] text-[#86948a]">Use the approved material database to build estimate inputs.</p><input aria-label="Search material list" value={materialSearch} onChange={(event) => setMaterialSearch(event.target.value)} placeholder="Search material or code" className="mt-3 w-full rounded-lg border border-[#2b3851] bg-[#131b2e] px-3 py-2 text-xs text-white placeholder:text-[#667085]" /><div className="mt-2 max-h-36 space-y-1 overflow-auto">{visibleMaterials.map((material) => <div key={material.code} className="flex items-center justify-between gap-2 rounded-lg bg-[#0a1220] p-2"><div className="min-w-0"><p className="truncate text-[10px] font-semibold text-white">{material.name}</p><p className="text-[9px] font-mono text-[#86948a]">{material.code} · {material.unit} · ${material.price.toFixed(2)}</p></div><button type="button" onClick={() => setEstimateMaterials((items) => items.includes(material.code) ? items : [...items, material.code])} className="shrink-0 rounded bg-[#4edea3] px-2 py-1 text-[9px] font-bold text-[#07101f]">Add</button></div>)}</div><p className="mt-3 text-[10px] text-[#4edea3]">{estimateMaterials.length} material items selected for estimate</p></section><section id="employee-rfis" className="scroll-mt-5 rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4 md:p-5"><div className="flex items-center gap-2"><MessageSquare className="h-4 w-4 text-[#f0b44d]" /><h2 className="text-sm font-semibold text-white">RFIs & responses</h2></div><div className="mt-4 rounded-xl bg-[#0a1220] p-3"><p className="text-xs font-semibold text-white">RFI-042 · Slab penetration detail</p><p className="mt-1 text-[10px] text-[#f0b44d]">Waiting for client response · Project BC-08-26</p><button type="button" className="mt-3 rounded-lg bg-[#7db2ff] px-3 py-2 text-[10px] font-bold text-[#07101f]">Open response thread</button></div></section></div>
          <section id="employee-reminders" className="scroll-mt-5 rounded-2xl border border-[#222a3d] bg-[#0d1728] p-4 md:p-5"><div className="flex items-center gap-2"><CalendarClock className="h-4 w-4 text-[#4edea3]" /><h2 className="text-sm font-semibold text-white">Reminders & leave</h2></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-[#0a1220] p-3 text-xs text-[#bbcabf]">Submit RFI-042 response before 4:00 PM</div><div className="rounded-xl bg-[#0a1220] p-3 text-xs text-[#bbcabf]">Review Metro Heights drawing revision</div><button type="button" onClick={() => setLeaveNotice('Leave request draft opened for manager approval.')} className="rounded-xl border border-[#2b3851] p-3 text-left text-xs font-semibold text-[#7db2ff]">Request leave {leaveNotice && <span className="mt-1 block text-[10px] text-[#4edea3]">{leaveNotice}</span>}</button></div></section>
          {adminMode && <section id="employee-admin" className="scroll-mt-5 rounded-2xl border border-[#7db2ff]/30 bg-[#0d1728] p-4 md:p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-mono uppercase tracking-wider text-[#7db2ff]">Admin controls</p><h2 className="mt-1 text-lg font-semibold text-white">Configure employee portal</h2></div><button type="button" onClick={() => setAdminMode(false)} aria-label="Close portal configuration"><X className="h-4 w-4 text-[#86948a]" /></button></div><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="rounded-xl bg-[#0a1220] p-3 text-xs text-[#bbcabf]">Portal role<select className="mt-2 w-full rounded-lg border border-[#2b3851] bg-[#131b2e] p-2 text-xs text-white"><option>Estimator employee</option><option>Team lead</option><option>Project manager</option></select></label><label className="rounded-xl bg-[#0a1220] p-3 text-xs text-[#bbcabf]">Default landing view<select className="mt-2 w-full rounded-lg border border-[#2b3851] bg-[#131b2e] p-2 text-xs text-white"><option>Overview</option><option>Estimation workspace</option><option>Assigned tasks</option></select></label><div className="rounded-xl bg-[#0a1220] p-3 text-xs text-[#bbcabf]"><p>Visible modules</p><div className="mt-2 space-y-2"><label className="flex items-center gap-2"><input type="checkbox" defaultChecked /> RFIs & responses</label><label className="flex items-center gap-2"><input type="checkbox" defaultChecked /> Leave requests</label><label className="flex items-center gap-2"><input type="checkbox" defaultChecked /> Material pricing</label></div></div></div><button type="button" className="mt-4 rounded-lg bg-[#7db2ff] px-4 py-2 text-xs font-bold text-[#07101f]">Save portal configuration</button></section>}
        </div></main>
      </div>
      {openTask && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#020611]/80 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-2xl border border-[#2b3851] bg-[#0d1728] p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-widest text-[#4edea3]">Task details</p><h2 className="mt-1 text-lg font-semibold text-white">{openTask.title}</h2><p className="mt-1 text-xs text-[#86948a]">{openTask.project} · {openTask.due}</p></div><button type="button" onClick={() => setOpenTask(null)} aria-label="Close task details"><X className="h-4 w-4 text-[#86948a]" /></button></div><a href={`data:text/plain;charset=utf-8,Files%20for%20${encodeURIComponent(openTask.project)}%0ATask%3A%20${encodeURIComponent(openTask.title)}`} download={`${openTask.project.replaceAll(' ', '-')}-task-files.txt`} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#4edea3] px-3 py-2 text-xs font-bold text-[#07101f]"><Download className="h-3.5 w-3.5" /> Download project files</a></div></div>}
    </div>
  );
}

export default EmployeePortalView;
