import { UserAuthAccount, UserRole, GeneratedCredentialsNotice, EmployeeItem, ClientItem, PartnerItem } from '../types';

/**
 * Generate a strong, secure random temporary password for newly registered users
 */
export function generateSecurePassword(role: UserRole, prefix: string): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789!@#$%';
  let randomPart = '';
  for (let i = 0; i < 6; i++) {
    randomPart += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  const roleCode = role.toUpperCase().slice(0, 3);
  return `BE-${roleCode}-${prefix ? prefix.slice(0, 3).toUpperCase() : 'SEC'}-${randomPart}!`;
}

/**
 * Initial standard user accounts representing each role in Bid Exact LLC
 */
export const INITIAL_USER_ACCOUNTS: UserAuthAccount[] = [
  // 1. OWNER / MANAGING PRINCIPAL
  {
    id: 'USR-OWNER-01',
    username: 'umer',
    email: 'umer@bidexact.com',
    name: 'Umer Khayam',
    role: 'owner',
    title: 'Founder & Managing Principal (Owner)',
    department: 'Executive Leadership',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    targetId: 'PARTNER-01',
    targetName: 'Umer Khayam (Bid Exact LLC 50% Equity)',
    createdAt: '2023-01-01',
    autoGeneratedPassword: 'OwnerPassword2026!',
    status: 'active',
  },
  // 2. HR & PEOPLE OPERATIONS
  {
    id: 'USR-HR-01',
    username: 'marcus.lee',
    email: 'marcus.lee@bidexact.com',
    name: 'Marcus Lee',
    role: 'hr',
    title: 'Head of HR & People Operations',
    department: 'People Operations & HR',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    targetId: 'EMP-116',
    targetName: 'Marcus Lee (HR Department)',
    createdAt: '2023-03-15',
    autoGeneratedPassword: 'HrPassword2026!',
    status: 'active',
  },
  // 3. EMPLOYEE / SENIOR BIM SPECIALIST
  {
    id: 'USR-EMP-102',
    username: 'elena.rostova',
    email: 'elena.rostova@bidexact.com',
    name: 'Elena Rostova',
    role: 'employee',
    title: 'Senior BIM / VDC Specialist',
    department: 'VDC & BIM',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    targetId: 'EMP-102',
    targetName: 'Elena Rostova (EMP-102)',
    createdAt: '2023-02-01',
    autoGeneratedPassword: 'ElenaPass2026!',
    status: 'active',
  },
  // 4. EMPLOYEE / ESTIMATOR
  {
    id: 'USR-EMP-101',
    username: 'marcus.vance',
    email: 'marcus.vance@bidexact.com',
    name: 'Marcus Vance',
    role: 'employee',
    title: 'Principal Lead Estimator',
    department: 'Estimating Operations',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    targetId: 'EMP-101',
    targetName: 'Marcus Vance (EMP-101)',
    createdAt: '2023-01-15',
    autoGeneratedPassword: 'MarcusPass2026!',
    status: 'active',
  },
  // 5. CLIENT / GENERAL CONTRACTOR (Turner Construction)
  {
    id: 'USR-CLIENT-01',
    username: 'turner.client',
    email: 'rsterling@turnerconstruction.com',
    name: 'Richard Sterling (Turner Construction)',
    role: 'client',
    title: 'VP Pre-Construction · Turner Construction',
    department: 'Tier-1 General Contractor Client',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
    targetId: 'client-1',
    targetName: 'Turner Construction',
    createdAt: '2023-04-10',
    autoGeneratedPassword: 'TurnerClient2026!',
    status: 'active',
  },
  // 6. CLIENT / SKANSKA USA
  {
    id: 'USR-CLIENT-02',
    username: 'skanska.client',
    email: 'mark.donovan@skanska.com',
    name: 'Mark Donovan (Skanska USA)',
    role: 'client',
    title: 'Lead Commercial Director · Skanska USA',
    department: 'Commercial Contractor Client',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
    targetId: 'client-2',
    targetName: 'Skanska USA',
    createdAt: '2023-05-20',
    autoGeneratedPassword: 'SkanskaClient2026!',
    status: 'active',
  },
  // 7. FINANCE & CONTROLLER
  {
    id: 'USR-FIN-01',
    username: 'sarah.jenkins',
    email: 'sarah.jenkins@bidexact.com',
    name: 'Sarah Jenkins',
    role: 'finance',
    title: 'Corporate Financial Controller',
    department: 'Finance & Legal',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    targetId: 'EMP-107',
    targetName: 'Sarah Jenkins (Finance & GL)',
    createdAt: '2023-04-12',
    autoGeneratedPassword: 'FinancePass2026!',
    status: 'active',
  }
];

const LOCAL_STORAGE_USERS_KEY = 'bid_exact_user_auth_accounts';
const LOCAL_STORAGE_SESSION_KEY = 'bid_exact_current_logged_in_user';
const LOCAL_STORAGE_CREDENTIAL_NOTICES_KEY = 'bid_exact_credential_notices';

/**
 * Get all user accounts stored in localStorage (or initialized defaults)
 */
export function getStoredUserAccounts(): UserAuthAccount[] {
  try {
    const raw = localStorage.getItem(LOCAL_STORAGE_USERS_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed;
      }
    }
  } catch (e) {
    console.error('Failed reading user accounts from localStorage', e);
  }
  // Initialize default
  localStorage.setItem(LOCAL_STORAGE_USERS_KEY, JSON.stringify(INITIAL_USER_ACCOUNTS));
  return INITIAL_USER_ACCOUNTS;
}

/**
 * Save user accounts to localStorage
 */
export function saveStoredUserAccounts(accounts: UserAuthAccount[]): void {
  try {
    localStorage.setItem(LOCAL_STORAGE_USERS_KEY, JSON.stringify(accounts));
  } catch (e) {
    console.error('Failed saving user accounts to localStorage', e);
  }
}

/**
 * Get active session user
 */
export function getActiveSessionUser(): UserAuthAccount {
  try {
    const raw = localStorage.getItem(LOCAL_STORAGE_SESSION_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      if (parsed && parsed.id && parsed.role) {
        return parsed;
      }
    }
  } catch (e) {
    console.error('Failed reading active session user', e);
  }
  // Default to Owner Umer Khayam
  const defaultOwner = INITIAL_USER_ACCOUNTS[0];
  localStorage.setItem(LOCAL_STORAGE_SESSION_KEY, JSON.stringify(defaultOwner));
  return defaultOwner;
}

/**
 * Set active session user
 */
export function setActiveSessionUser(user: UserAuthAccount): void {
  try {
    localStorage.setItem(LOCAL_STORAGE_SESSION_KEY, JSON.stringify(user));
  } catch (e) {
    console.error('Failed saving active session user', e);
  }
}

/**
 * Get generated credential notices
 */
export function getCredentialNotices(): GeneratedCredentialsNotice[] {
  try {
    const raw = localStorage.getItem(LOCAL_STORAGE_CREDENTIAL_NOTICES_KEY);
    if (raw) {
      return JSON.parse(raw);
    }
  } catch (e) {
    console.error('Failed reading credential notices', e);
  }
  return [];
}

/**
 * Save generated credential notice
 */
export function addCredentialNotice(notice: GeneratedCredentialsNotice): void {
  try {
    const existing = getCredentialNotices();
    const updated = [notice, ...existing];
    localStorage.setItem(LOCAL_STORAGE_CREDENTIAL_NOTICES_KEY, JSON.stringify(updated));
  } catch (e) {
    console.error('Failed saving credential notice', e);
  }
}

/**
 * Automatically provision credentials when an employee is registered
 */
export function provisionEmployeeLogin(employee: EmployeeItem): { user: UserAuthAccount; notice: GeneratedCredentialsNotice } {
  const username = employee.email.split('@')[0] || employee.name.toLowerCase().replace(/\s+/g, '.');
  const tempPassword = generateSecurePassword('employee', employee.id);
  
  // If HR manager or leadership, assign HR or Employee role appropriately
  const isHr = employee.department === 'Finance & Legal' && employee.role.toLowerCase().includes('hr');
  const role: UserRole = isHr ? 'hr' : 'employee';

  const user: UserAuthAccount = {
    id: `USR-${employee.id}`,
    username,
    email: employee.email,
    name: employee.name,
    role,
    title: employee.role,
    department: employee.department,
    targetId: employee.id,
    targetName: `${employee.name} (${employee.id})`,
    createdAt: new Date().toISOString().slice(0, 10),
    autoGeneratedPassword: tempPassword,
    status: 'active',
  };

  const notice: GeneratedCredentialsNotice = {
    id: `NOTIF-CRED-${Date.now()}`,
    userId: user.id,
    name: employee.name,
    email: employee.email,
    role,
    tempPassword,
    targetEntityName: `${employee.name} · ${employee.role}`,
    createdAt: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    sentStatus: 'sent',
  };

  // Persist
  const allUsers = getStoredUserAccounts();
  const filtered = allUsers.filter(u => u.id !== user.id && u.email !== user.email);
  saveStoredUserAccounts([user, ...filtered]);
  addCredentialNotice(notice);

  return { user, notice };
}

/**
 * Automatically provision credentials when a client is registered
 */
export function provisionClientLogin(client: ClientItem): { user: UserAuthAccount; notice: GeneratedCredentialsNotice } {
  const cleanClientName = client.name.toLowerCase().replace(/[^a-z0-9]/g, '');
  const username = `${cleanClientName}.portal`;
  const email = client.contact.email || `portal@${cleanClientName}.com`;
  const tempPassword = generateSecurePassword('client', client.id);

  const user: UserAuthAccount = {
    id: `USR-${client.id}`,
    username,
    email,
    name: `${client.contact.name} (${client.name})`,
    role: 'client',
    title: client.contact.title || 'Client Pre-Construction Director',
    department: 'Enterprise Client Account',
    targetId: client.id,
    targetName: client.name,
    createdAt: new Date().toISOString().slice(0, 10),
    autoGeneratedPassword: tempPassword,
    status: 'active',
  };

  const notice: GeneratedCredentialsNotice = {
    id: `NOTIF-CRED-${Date.now()}`,
    userId: user.id,
    name: client.contact.name || client.name,
    email,
    role: 'client',
    tempPassword,
    targetEntityName: `${client.name} (Contact: ${client.contact.name})`,
    createdAt: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    sentStatus: 'sent',
  };

  // Persist
  const allUsers = getStoredUserAccounts();
  const filtered = allUsers.filter(u => u.id !== user.id && u.email !== user.email);
  saveStoredUserAccounts([user, ...filtered]);
  addCredentialNotice(notice);

  return { user, notice };
}
